# Yomitan

Yomitan on browser-lisäosa, joka mahdollistaa nopeasti sanojen merkityksen tarkistamisen ja niiden siirtämisen Ankiin. 

## Asennus

Lataa Yomitan käyttämällesi browserille (Chrome ja Firefox sopivimmat)
https://yomitan.wiki/

## Asetukset 

Lataa seuraava tiedosto: <a href="_main_files/yomitansettings.json" download="yomitansettings.json">Download Yomitan Settings JSON</a>

- Backup -> Import settings 
- Valitse Active profile -> japani, jos opiskelet japania; muussa tapauksessa valitse Muut

## Valitse opiskelemasi kieli

General -> Language

## Yomitanin sanakirjat 

Jos opiskelet japania, lataa seuraava tiedosto: https://mega.nz/file/CZphmChT#UnCJbgXTxqoMfDeF6lhjdmtQCUQPAvqMS-Tc8vg6hew

- Backup -> Import dictionary collection

- Aseta Configure installed and enabled dictionarys -kohdasta tämän jälkeen kaikki yllä olevat sanakirjat päälle 

Jos opiskelet jotain muuta, Yomitan suosittelee sopivat sanakirjat.

- Get recommended dictionarys -> lataa suositellut.

- Tämän jälkeen Configure installed and enabled dictionarys -> laita kyseinen sanakirja päälle. 

## Ankiin yhdistäminen ja korttien säätäminen {#Ankiin-yhdistaminen-ja-korttien-saataminen}

- Enable Anki integration (Ankin tulee olla päällä samaan aikaan)

- Configure Anki flashcards -> Deck-kohtaan louhintaa varten luomasi pakan nimi

- Maindefinition-kohtaan tärkein lataamasi sanakirja (Japanin opiskelijoille jo valmiiksi asetettu, muille kielille laita tähän kohtaan lataamasti sanakirjan nimi)
